// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: alarm/alarm.proto

package alarm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CameraType int32

const (
	CameraType_Unknown CameraType = 0
	CameraType_DaHua   CameraType = 1
	CameraType_HiK     CameraType = 2
)

// Enum value maps for CameraType.
var (
	CameraType_name = map[int32]string{
		0: "Unknown",
		1: "DaHua",
		2: "HiK",
	}
	CameraType_value = map[string]int32{
		"Unknown": 0,
		"DaHua":   1,
		"HiK":     2,
	}
)

func (x CameraType) Enum() *CameraType {
	p := new(CameraType)
	*p = x
	return p
}

func (x CameraType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CameraType) Descriptor() protoreflect.EnumDescriptor {
	return file_alarm_alarm_proto_enumTypes[0].Descriptor()
}

func (CameraType) Type() protoreflect.EnumType {
	return &file_alarm_alarm_proto_enumTypes[0]
}

func (x CameraType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CameraType.Descriptor instead.
func (CameraType) EnumDescriptor() ([]byte, []int) {
	return file_alarm_alarm_proto_rawDescGZIP(), []int{0}
}

type ResponseCode int32

const (
	ResponseCode_Ok_200                ResponseCode = 0 // successed
	ResponseCode_Err_Parameter_invalid ResponseCode = 1 // invalid parameter
	ResponseCode_Err_Device_No_Found   ResponseCode = 2 // device not found
	ResponseCode_Err_500               ResponseCode = 3 // server inner failed
)

// Enum value maps for ResponseCode.
var (
	ResponseCode_name = map[int32]string{
		0: "Ok_200",
		1: "Err_Parameter_invalid",
		2: "Err_Device_No_Found",
		3: "Err_500",
	}
	ResponseCode_value = map[string]int32{
		"Ok_200":                0,
		"Err_Parameter_invalid": 1,
		"Err_Device_No_Found":   2,
		"Err_500":               3,
	}
)

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}

func (x ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_alarm_alarm_proto_enumTypes[1].Descriptor()
}

func (ResponseCode) Type() protoreflect.EnumType {
	return &file_alarm_alarm_proto_enumTypes[1]
}

func (x ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCode.Descriptor instead.
func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_alarm_alarm_proto_rawDescGZIP(), []int{1}
}

// The request message
type AlarmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        CameraType `protobuf:"varint,1,opt,name=type,proto3,enum=alarm.CameraType" json:"type,omitempty"`
	SzIP        string     `protobuf:"bytes,2,opt,name=szIP,proto3" json:"szIP,omitempty"`
	NPort       uint32     `protobuf:"varint,3,opt,name=nPort,proto3" json:"nPort,omitempty"`
	SzUserName  string     `protobuf:"bytes,4,opt,name=szUserName,proto3" json:"szUserName,omitempty"`
	SzPassword  string     `protobuf:"bytes,5,opt,name=szPassword,proto3" json:"szPassword,omitempty"`
	DownloadUrl string     `protobuf:"bytes,6,opt,name=downloadUrl,proto3" json:"downloadUrl,omitempty"`
	FileName    string     `protobuf:"bytes,7,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Md5Value    string     `protobuf:"bytes,8,opt,name=md5Value,proto3" json:"md5Value,omitempty"`
}

func (x *AlarmRequest) Reset() {
	*x = AlarmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alarm_alarm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmRequest) ProtoMessage() {}

func (x *AlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alarm_alarm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmRequest.ProtoReflect.Descriptor instead.
func (*AlarmRequest) Descriptor() ([]byte, []int) {
	return file_alarm_alarm_proto_rawDescGZIP(), []int{0}
}

func (x *AlarmRequest) GetType() CameraType {
	if x != nil {
		return x.Type
	}
	return CameraType_Unknown
}

func (x *AlarmRequest) GetSzIP() string {
	if x != nil {
		return x.SzIP
	}
	return ""
}

func (x *AlarmRequest) GetNPort() uint32 {
	if x != nil {
		return x.NPort
	}
	return 0
}

func (x *AlarmRequest) GetSzUserName() string {
	if x != nil {
		return x.SzUserName
	}
	return ""
}

func (x *AlarmRequest) GetSzPassword() string {
	if x != nil {
		return x.SzPassword
	}
	return ""
}

func (x *AlarmRequest) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *AlarmRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AlarmRequest) GetMd5Value() string {
	if x != nil {
		return x.Md5Value
	}
	return ""
}

// The response message
type AlarmReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=alarm.ResponseCode" json:"code,omitempty"`
	Message string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AlarmReply) Reset() {
	*x = AlarmReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alarm_alarm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlarmReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmReply) ProtoMessage() {}

func (x *AlarmReply) ProtoReflect() protoreflect.Message {
	mi := &file_alarm_alarm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmReply.ProtoReflect.Descriptor instead.
func (*AlarmReply) Descriptor() ([]byte, []int) {
	return file_alarm_alarm_proto_rawDescGZIP(), []int{1}
}

func (x *AlarmReply) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_Ok_200
}

func (x *AlarmReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_alarm_alarm_proto protoreflect.FileDescriptor

var file_alarm_alarm_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x2f, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x22, 0xf9, 0x01, 0x0a, 0x0c, 0x41,
	0x6c, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x61, 0x6c, 0x61, 0x72,
	0x6d, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x7a, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x73, 0x7a, 0x49, 0x50, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x50, 0x6f, 0x72, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6e, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x7a, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x7a, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x7a, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x7a, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x64,
	0x35, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x64,
	0x35, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4f, 0x0a, 0x0a, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x13, 0x2e, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x2d, 0x0a, 0x0a, 0x43, 0x61, 0x6d, 0x65, 0x72,
	0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x61, 0x48, 0x75, 0x61, 0x10, 0x01, 0x12, 0x07, 0x0a,
	0x03, 0x48, 0x69, 0x4b, 0x10, 0x02, 0x2a, 0x5b, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x6b, 0x5f, 0x32, 0x30, 0x30,
	0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x72, 0x72, 0x5f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x01, 0x12, 0x17, 0x0a,
	0x13, 0x45, 0x72, 0x72, 0x5f, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x4e, 0x6f, 0x5f, 0x46,
	0x6f, 0x75, 0x6e, 0x64, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x5f, 0x35, 0x30,
	0x30, 0x10, 0x03, 0x32, 0x4b, 0x0a, 0x0c, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x13, 0x2e, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x2e, 0x41,
	0x6c, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x61, 0x6c,
	0x61, 0x72, 0x6d, 0x2e, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c,
	0x73, 0x72, 0x6f, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x61, 0x6c, 0x61, 0x72, 0x6d,
	0x2f, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alarm_alarm_proto_rawDescOnce sync.Once
	file_alarm_alarm_proto_rawDescData = file_alarm_alarm_proto_rawDesc
)

func file_alarm_alarm_proto_rawDescGZIP() []byte {
	file_alarm_alarm_proto_rawDescOnce.Do(func() {
		file_alarm_alarm_proto_rawDescData = protoimpl.X.CompressGZIP(file_alarm_alarm_proto_rawDescData)
	})
	return file_alarm_alarm_proto_rawDescData
}

var file_alarm_alarm_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_alarm_alarm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_alarm_alarm_proto_goTypes = []interface{}{
	(CameraType)(0),      // 0: alarm.CameraType
	(ResponseCode)(0),    // 1: alarm.ResponseCode
	(*AlarmRequest)(nil), // 2: alarm.AlarmRequest
	(*AlarmReply)(nil),   // 3: alarm.AlarmReply
}
var file_alarm_alarm_proto_depIdxs = []int32{
	0, // 0: alarm.AlarmRequest.type:type_name -> alarm.CameraType
	1, // 1: alarm.AlarmReply.code:type_name -> alarm.ResponseCode
	2, // 2: alarm.AlarmService.SetAlarmMessage:input_type -> alarm.AlarmRequest
	3, // 3: alarm.AlarmService.SetAlarmMessage:output_type -> alarm.AlarmReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_alarm_alarm_proto_init() }
func file_alarm_alarm_proto_init() {
	if File_alarm_alarm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alarm_alarm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlarmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alarm_alarm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlarmReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alarm_alarm_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alarm_alarm_proto_goTypes,
		DependencyIndexes: file_alarm_alarm_proto_depIdxs,
		EnumInfos:         file_alarm_alarm_proto_enumTypes,
		MessageInfos:      file_alarm_alarm_proto_msgTypes,
	}.Build()
	File_alarm_alarm_proto = out.File
	file_alarm_alarm_proto_rawDesc = nil
	file_alarm_alarm_proto_goTypes = nil
	file_alarm_alarm_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AlarmServiceClient is the client API for AlarmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AlarmServiceClient interface {
	// call alarm interface
	SetAlarmMessage(ctx context.Context, in *AlarmRequest, opts ...grpc.CallOption) (*AlarmReply, error)
}

type alarmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlarmServiceClient(cc grpc.ClientConnInterface) AlarmServiceClient {
	return &alarmServiceClient{cc}
}

func (c *alarmServiceClient) SetAlarmMessage(ctx context.Context, in *AlarmRequest, opts ...grpc.CallOption) (*AlarmReply, error) {
	out := new(AlarmReply)
	err := c.cc.Invoke(ctx, "/alarm.AlarmService/SetAlarmMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlarmServiceServer is the server API for AlarmService service.
type AlarmServiceServer interface {
	// call alarm interface
	SetAlarmMessage(context.Context, *AlarmRequest) (*AlarmReply, error)
}

// UnimplementedAlarmServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAlarmServiceServer struct {
}

func (*UnimplementedAlarmServiceServer) SetAlarmMessage(context.Context, *AlarmRequest) (*AlarmReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAlarmMessage not implemented")
}

func RegisterAlarmServiceServer(s *grpc.Server, srv AlarmServiceServer) {
	s.RegisterService(&_AlarmService_serviceDesc, srv)
}

func _AlarmService_SetAlarmMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).SetAlarmMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alarm.AlarmService/SetAlarmMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).SetAlarmMessage(ctx, req.(*AlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AlarmService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "alarm.AlarmService",
	HandlerType: (*AlarmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetAlarmMessage",
			Handler:    _AlarmService_SetAlarmMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alarm/alarm.proto",
}
